version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    networks:
    -  nodejs_express_mongo_angular12_api-network
    ports:
    - "9090:9090"
    volumes:
    - ./servidor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    # depends_on:
    # - myapp_practica
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_practica
    networks:
    -  nodejs_express_mongo_angular12_api-network
    ports:
    - "3500:3000"
    # - "3500:3000"
    volumes:
    - ./servidor/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - myGrafanaVol:/var/lib/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"  #Deshabilitar el login de acceso a Grafana
      GF_AUTH_ANONYMOUS_ENABLED: "true"   #Permitir la autenticaci贸n an贸nima
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin #Que el rol de autenticaci贸n an贸nima sea Admin
      GF_INSTALL_PLUGINS: grafana-clock-panel 1.0.1 #Que instale el plugin grafana-clock-panel 1.0.1
    depends_on:
    - prometheus
volumes:
  myGrafanaVol:
networks:
   nodejs_express_mongo_angular12_api-network:
    external: true