version: "3"
services:
  angular:
    build: ./cliente
    ports:
      - 4200:4200
    networks:
      - bualabob
  graphql:
    build: ./servidor/graphQL
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      DB_MONGO: mongodb://mongo:27017/bualabob
      PORT: 3000 
    networks:
      - bualabob
  rest:
    build: ./servidor/rest
    depends_on:
      - mongo
    ports:
      - 4000:4000
    environment:
      DB_MONGO: mongodb://mongo:27017/bualabob 
    networks:
      - bualabob
  mongo:
    image: mongo
    volumes:
      - ./dump:/var/dump
    command: mongorestore --host mongo:27017 --db bualabob /var/dump/bualabob

    ports:
      - 27017:27017
    networks:
      - bualabob
networks:
  bualabob:
    driver: bridge
